config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :contracts

  root to: 'contracts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
  before_destroy :delete_documents

  has_one_attached :document

  validates :number, presence: true
  validates :firstname, presence: true, length: { maximum: 255 }
  validates :lastname, presence: true, length: { maximum: 255 }
  validates :register, format: { with: /[A-Яа-яЁёҮүӨө]{2}+[0-9]{8}\z/ } 
  validates :address, presence: true, length: { maximum: 255 }

  scope :created_at_desc, lambda {
    order(created_at: :desc)
  }

  private

  def delete_documents
    document.purge
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy]

  def index
    @contracts = Contract.created_at_desc.page(params[:page])
  end

  def show
  end

  def new
    @contract = Contract.new
  end

  def create
    @contract = Contract.new(contract_params)
    if @contract.save
      redirect_to ({ action: :index }), notice: "Амжилттай үүсгэлээ"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @contract.update_attributes(contract_params)
      redirect_to ({ action: :index }), notice: "Амжилттай заслаа"
    else
      render :edit
    end
  end

  def destroy
    @contract.destroy!
    redirect_to ({ action: :index }), notice: "Амжилттай устгагдлаа"
  end

  private

  def contract_params
    params.require(:contract).permit(:number, :lastname, :firstname, :register, :address, :document)
  end

  def set_contract
    @contract = Contract.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contracts/edit.html.erb
<div class="content-wrapper">
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <%= link_to 'Буцах', :back, class: 'btn btn-danger' %>
            </div>
            <div class="card-body">

              <%= render 'layouts/errors', model: @contract %>

              <%= form_for @contract, url: contract_path(@contract), method: :patch, multipart: true do |f| %>
                <div class="card-body">

                  <div class="form-group">
                    <%= f.text_field :number, { class: 'form-control', placeholder: 'Гэрээний дугаар'} %>
                  </div>

                  <div class="form-group">
                    <div class="row">
                      <div class="col-4">
                        <%= f.text_field :lastname, { class: 'form-control', placeholder: 'Овог'} %>
                      </div>
                      <div class="col-4">
                        <%= f.text_field :firstname, { class: 'form-control', placeholder: 'Нэр'} %>
                      </div>
                      <div class="col-4">
                        <%= f.text_field :register, { class: 'form-control', placeholder: 'Регистер'} %>
                      </div>
                    </div>
                  </div>

                  <div class="form-group">
                    <%= f.text_field :address, { class: 'form-control', placeholder: 'Хаяг'} %>
                  </div>

                  <div class="form-group">
                    <div class="input-group">
                      <div class="custom-file">
                        <%= f.file_field :document, class: 'custom-file-input', 
                            accept: ".doc, .docx,.txt,.pdf" %>
                        <label class="custom-file-label">Гэрээний файл сонгоно уу</label>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="card-footer">
                  <%= f.submit 'Засах', class: 'btn btn-primary' %>
                </div>

              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/contracts/index.html.erb
<div class="content-wrapper">
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">

          <%= render 'layouts/alerts' %>

          <div class="card">
            <div class="card-header">
              <%= link_to 'Нэмэх', new_contract_path, class: 'btn btn-success' %>
            </div>
            <div class="card-body">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th>Гэрээний дугаар</th>
                    <th>Нэр</th>
                    <th>Хаяг</th>
                    <th>Үйлдэл</th>
                  </tr>
                </thead>
                <tbody>
                  <% @contracts.each do |contract| %>
                    <tr>
                      <td><%= contract.number %></td>
                      <td><%= contract.firstname %> <%= contract.lastname %></td>
                      <td><%= contract.address %></td>
                      <td>
                        <%= link_to contract_path(contract), class: 'btn btn-primary btn-sm text-white' do %>
                          <i class="fa fa-eye"></i>
                        <% end %>

                        <%= link_to edit_contract_path(contract), class: 'btn btn-warning btn-sm text-white' do %>
                          <i class="fa fa-pencil"></i>
                        <% end %>

                        <%= link_to contract_path(contract), class: 'btn btn-danger btn-sm text-white', method: :delete,  data: { confirm: 'Are you sure?'}, rel: 'nofollow' do %>
                          <i class="fa fa-trash-o"></i>
                        <% end %>
                      </td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <div class="card-footer clearfix">
                <%= paginate @contracts %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

app/views/contracts/new.html.erb
<div class="content-wrapper">
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <%= link_to 'Буцах', :back, class: 'btn btn-danger' %>
            </div>
            <div class="card-body">

              <%= render 'layouts/errors', model: @contract %>

              <%= form_for @contract, url: contracts_path, method: :post, multipart: true do |f| %>
                <div class="card-body">

                  <div class="form-group">
                    <%= f.text_field :number, { class: 'form-control', placeholder: 'Гэрээний дугаар'} %>
                  </div>

                  <div class="form-group">
                    <div class="row">
                      <div class="col-4">
                        <%= f.text_field :lastname, { class: 'form-control', placeholder: 'Овог'} %>
                      </div>
                      <div class="col-4">
                        <%= f.text_field :firstname, { class: 'form-control', placeholder: 'Нэр'} %>
                      </div>
                      <div class="col-4">
                        <%= f.text_field :register, { class: 'form-control', placeholder: 'Регистер'} %>
                      </div>
                    </div>
                  </div>

                  <div class="form-group">
                    <%= f.text_field :address, { class: 'form-control', placeholder: 'Хаяг'} %>
                  </div>

                  <div class="form-group">
                    <div class="input-group">
                      <div class="custom-file">
                        <%= f.file_field :document, class: 'custom-file-input', 
                            accept: ".doc, .docx,.txt,.pdf" %>
                        <label class="custom-file-label">Гэрээний файл сонгоно уу</label>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="card-footer">
                  <%= f.submit 'Нэмэх', class: 'btn btn-primary' %>
                </div>

              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/contracts/show.html.erb
<div class="content-wrapper">
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">

          <%= render 'layouts/alerts' %>

          <div class="card">
            <div class="card-header">
              <%= link_to 'Буцах', :back, class: 'btn btn-danger' %>
            </div>
            <div class="card-body">
              <p><b>Гэрээний дугаар: </b><%= @contract.number %></p>
              <p><b>Овог: </b><%= @contract.lastname %></p>
              <p><b>Нэр: </b><%= @contract.firstname %></p>
              <p><b>Регистер: </b><%= @contract.register %></p>
              <p><b>Хаяг: </b><%= @contract.address %></p>
              <br />
              <%= link_to @contract.document.blob.filename, url_for(@contract.document), target: '_blank' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/layouts/_alerts.html.erb
<% flash.each do |key, value| %>
  <%
    class_name = (case key when 'notice' then 'success' when 'alert' then 'danger' else key end)
    if value.kind_of?(String)
      value = [value]
    elsif value.kind_of?(Array)
    else
      next
    end
  %>
    <% value.each do |v| %>
      <div class="alert alert-<%= class_name %> alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= v %>
      </div>
    <% end %>
<% end %>

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contractweb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>